### ISSUE TITLE
add negative Quarternions

### ISSUE THREAD

**Issue by birkschmithuesen** [birkschmithuesen/MergingEntities#11]
* right now we just take the positive value from the quarternions, to not have the problem, that each orientation of the MPU has two representations in Quarternions
* since we are loosing half the value space with this method, in the future we should take the absolute numbers and compute the second values for each position
* this is done, by taking the Quarternions vector und multiply it with -1

**Comment by danieldalfovo** [comment]
same here like previous issue.

**Comment by birkschmithuesen** [comment]
same like answer on previous issue. I also made a video message for this.

**Comment by danieldalfovo** [comment]
working with quaternions is in my opinion the best way, or a transformation matrix. Euler rotations have some limitations (gimbal lock) and also behave strange in given circumstances when transitioning from one position to another. Also in regards to Unity, I can imagine the motion of the virtual dancers are described with quaternions? We should match these.

**Comment by birkschmithuesen** [comment]
Yes, I agree quartions is the way to go. Also unity is working with quarternions as far as I know. But as we process them right now in TouchDesigner I'm not sure if we are loosing 50% of position data, or not. When you check my video message you will understand what I mean

**Comment by birkschmithuesen** [comment]
Yes, I agree quartions is the way to go. Also unity is working with quarternions as far as I know. But as we process them right now in TouchDesigner I'm not sure if we are loosing 50% of position data, or not. When you check my video message you will understand what I mean

**Comment by birkschmithuesen** [comment]
rotation matrix did the trick
