### ISSUE TITLE
video camera stream has very high latency

### ISSUE THREAD

**Issue by birkschmithuesen** [birkschmithuesen/MergingEntities#113]
when compared with a normal "video in", the latency feels 3 times higher

**Comment by danieldalfovo** [comment]
interesting. i definitely see the difference too. the cook time of the video in inside the engine comp is not quite but almost as low as the one outside the engine. so the observeable difference could be the time the engine needs to push the pixels from the engine process to the main process.

**Comment by danieldalfovo** [comment]
i checked and used a touch out from the engine and a touch in inside the main toe. definitely quicker :-/
