### ISSUE TITLE
OSC check-in endpoint

### ISSUE THREAD

**Issue by tpltnt** [birkschmithuesen/MergingEntities#25]
In order to be sure that the current setup is internally compatible,
As a director
I want a check-in feature for new controllers in a setup
Whereas currently I don't know if the controller runs a compatible firmware version and the controller can correctly make sense of the data transmitted.

I had the following scenario in mind: a performance is running, one controller fails and a backup controller is brought online. This controller unfortunately has been flashed with an incompatible firmware version and thus the surrounding system (e.g. sound synthesis) does not work as expected. This feature is meant as an extra layer of quality control and (early) trigger to narrow down problems.

**Comment by birkschmithuesen** [comment]
that's advanced. L0ve it!
