### ISSUE TITLE
PR #74 broke the code #74 from tpltnt/halt-boot-unsuitable-sensors 

### ISSUE THREAD

**Issue by system-failed** [birkschmithuesen/MergingEntities#76]
Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1284
load:0x40078000,len:12808
load:0x40080400,len:3032
entry 0x400805e4
----------------------------------------
  ┌─┐┬─┐┌┬┐┌─┐┌─┐  ┌┬┐┌─┐┌┐ ┬┬  ┌─┐┌─┐
  ├─┤├┬┘ │ ├┤ └─┐  ││││ │├┴┐││  ├┤ └─┐
  ┴ ┴┴└─ ┴ └─┘└─┘  ┴ ┴└─┘└─┘┴┴─┘└─┘└─┘
----------------------------------------

setting up LED pins ... done
Connecting to wifi network "ArtNet4Hans" ........ succeeded
local IP address is 192.168.0.100
Starting UDP connection to local port 8888 ... succeeded
target OSC server is 192.168.0.2 port 8000
setting up I2C pins ... done
setting up sensor sockets ... done
setting up gyro for headGuru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400d68ce  PS      : 0x00060830  A0      : 0x800d6bb3  A1      : 0x3ffb2700  
A2      : 0x00000000  A3      : 0x00000068  A4      : 0x00000000  A5      : 0x00000100  
A6      : 0x3ffcb9c8  A7      : 0x00000000  A8      : 0x8008cfb0  A9      : 0x3ffb26d0  
A10     : 0x3ffc4f28  A11     : 0x00000000  A12     : 0x00000000  A13     : 0x00000001  
A14     : 0x00000001  A15     : 0x00000001  SAR     : 0x00000020  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000134  LBEG    : 0x40089b30  LEND    : 0x40089b46  LCOUNT  : 0xffffffff  

Backtrace:0x400d68cb:0x3ffb27000x400d6bb0:0x3ffb2730 0x400d3cc4:0x3ffb2750 0x400d3d2b:0x3ffb2770 0x400d5868:0x3ffb2790 0x400d59b2:0x3ffb27b0 0x400d64f6:0x3ffb27d0 0x400dafb2:0x3ffb2820 

ELF file SHA256: 0000000000000000

Rebooting...
ets Jun  8 2016 00:22:57

**Comment by tpltnt** [comment]
not part of current development tree and linked to deprecated sensors
